{
 "title": "Gateway dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "d_environment",
    "label": "Environment:",
    "query": {
     "query": "label_values(system_uptime,environment)"
    }
   },
   {
    "name": "d_hostname",
    "label": "Hostname:",
    "query": {
     "query": "label_values(system_uptime{environment=~\"$d_environment\"},host_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$d_hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "d_hostname" },
  {
   "title": "Role",
   "type": "stat",
   "description": "Machine Role",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_role{role=~\".+\", host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Basics",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_paging_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", state=\"used\"}/ ignoring (state) system_paging_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"} * 100",
     "legendFormat": "SWAP"
    },
    {
     "expr": "system_filesystem_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", mountpoint=\"/\", service_namespace=\"vs_id_0\", state=\"used\"}/ ignoring (state) system_filesystem_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", mountpoint=\"/\", service_namespace=\"vs_id_0\"} * 100",
     "legendFormat": "ROOT FS"
    },
    {
     "expr": "system_filesystem_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", mountpoint=\"/var/log\", service_namespace=\"vs_id_0\", state=\"used\"}/ ignoring (state) system_filesystem_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", mountpoint=\"/var/log\", service_namespace=\"vs_id_0\"} * 100",
     "legendFormat": "LOGS FS"
    },
    {
     "expr": "AVG(100-system_cpu_utilization{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", state=\"idle\"})",
     "legendFormat": "AVE CPU"
    },
    {
     "expr": "system_memory_usage{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", state=\"used\"}/ ignoring (state) system_memory_limit{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"} * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Cluster Member State",
   "type": "table",
   "description": "Cluster state",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "cluster_xl_members_state{environment=~\"$d_environment\", id!~\".\"}"
    }
   ]
  },
  {
   "title": "Core Mappting",
   "type": "table",
   "description": "CoreXL / SecureXL CPU core split",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "system_cpu_utilization{environment=~\"$d_environment\", host_name=~\"$d_hostname\", state=\"idle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "description": "Version of the OS",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_version{version=~\".+\", host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "stat",
   "description": "Hardware Model",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_model{model=~\".+\", host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Blades Status",
   "type": "table",
   "description": "Blades enabled or not",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 6 },
   "targets": [
    {
     "expr": "blades_update_state{host_name=~\"gw91\", environment=~\"Default\"}",
     "legendFormat": "{{entity}}"
    }
   ]
  },
  {
   "title": "Blade update",
   "type": "table",
   "description": "Blade update status",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "1000 * blades_update_time{host_name=~\"$d_hostname\", environment=~\"$d_environment\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy Installed",
   "type": "stat",
   "description": "Installed policy name",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "firewall_policy_name{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Identity Awareness",
   "type": "bargauge",
   "description": "User and machine ID count",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(entity) (ida_authenticated{environment=~\"$d_environment\", host_name=~\"$d_hostname\", entity=\"User\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(entity) (ida_authenticated{environment=~\"$d_environment\", host_name=~\"$d_hostname\", entity=\"Machine\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Policy date",
   "type": "stat",
   "description": "Time of last policy installation",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(firewall_policy_time{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}>100000)*1000"
    }
   ]
  },
  {
   "title": "CPU usage per core",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(cpu) (100 - system_cpu_utilization{environment=~\"$d_environment\", host_name=~\"$d_hostname\", state=\"idle\"})",
     "legendFormat": "CPU-{{cpu}}"
    }
   ]
  },
  {
   "title": "VPN clients",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_network_blades_vpn_active_clients{environment=~\"$d_environment\", host_name=\"$d_hostname\"}",
     "legendFormat": "Active Clients"
    }
   ]
  },
  {
   "title": "Concurrent Connections",
   "type": "timeseries",
   "description": "Concurrent Connections",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_network_connections{environment=~\"$d_environment\", host_name=~\"$d_hostname\", component=\"FW\"}",
     "legendFormat": "Conns"
    }
   ]
  },
  {
   "title": "New Connection Rate",
   "type": "timeseries",
   "description": "New connection rate per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "/s" } },
   "targets": [
    {
     "expr": "system_network_connections_rate{environment=~\"$d_environment\", host_name=\"$d_hostname\", component=\"Host\"}",
     "legendFormat": "CPS"
    }
   ]
  },
  {
   "title": "Total throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "system_network_interface_io_transmit_rate{environment=~\"$d_environment\", host_name=~\"$d_hostname\", interface=\"TOTAL\"}",
     "legendFormat": "Total TX"
    },
    {
     "expr": "system_network_interface_io_receive_rate{environment=~\"$d_environment\", host_name=~\"$d_hostname\", interface=\"TOTAL\"}",
     "legendFormat": "Total RX"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "sum by (interface) (system_network_interface_io_receive_rate{host_name=~\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "RX {{interface}}"
    },
    {
     "expr": "sum by (interface) (system_network_interface_io_transmit_rate{host_name=~\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "TX {{interface}}"
    }
   ]
  }
 ]
}